### ISSUE TITLE
Fails with react 15.x+ (at least)

### ISSUE THREAD

**Issue by imbroglioj** [wix/gulp-react-templates#11]
The react-templates version used produces code that "requires('react/addons')" but the addons module version no longer exists at least since react 15.x.  
Modifying the package.json react-templates version to 0.6.1 resolves the problem. I have made a temporary fork which seems to solve the problem.

**Comment by rileylnapier** [comment]
would love to see your fork land

**Comment by idok** [comment]
landed and published
