### ISSUE TITLE
more useful error messages?

### ISSUE THREAD

**Issue by splitbrain** [wix/gulp-react-templates#8]
Hi,

whenever there's some error in my template, I get a message like this:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
RTCodeError: Line 3: Unexpected identifier
```

Which isn't really helpful. I wonder if that's a problem of RT or of the way gulp-RT calls it. Is there any way to get more useful messages (eg, printing the correct line that caused the error)?

**Comment by idok** [comment]
try to run the rt cli with the file and see if the error improves

**Comment by splitbrain** [comment]
Yeah seems like the error isn't more helpful in rt itself.

**Comment by idok** [comment]
You can open an issue in react-templates
