### ISSUE TITLE
gulp-react-templates out of date resulting in incompatible dependency versions

### ISSUE THREAD

**Issue by pants97** [wix/gulp-react-templates#9]
Hello,

a clean installation of "gulp-react-templates" results in a broken install of version 0.1.0.

Cause: Dependency "react-templates" is pulled with version 0.2.1, which in turn requires dependency "escodegen@^1.7.0" (note the circumflex), as stated in "package.json" of react-templates. So actually the most current version escodegen@1.8 is pulled. However, escodegen@1.8 has some breaking changes, i.e. the addition of "ExportDeclaration" as parser token. This addition to escodegen is not supported by react-templates@0.2.1, causing gulp to fail.

Apparently the most current version of react-templates@0.4.x fixes that break by changing its dependencies to require "escodegen@1.7.1" (no more circumflex), as can be seen in this commit: https://github.com/wix/react-templates/commit/f79cb7632bdb2ed554e5f0e8624f28ab9771ebe7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 (SHA-1: f79cb7632bdb2ed554e5f0e8624f28ab9771ebe7) on 2015-12-29.

I worked around by explicitly adding "escodegen": "1.7.1" to my project's package.json.

Can you fix this?

Thanks so much!
Best,
Alex

**Comment by idok** [comment]
fixed with https://github.com/wix/gulp-react-templates/commit/2105ac7a6657f38ea59b66c13d1eeec138a98295

**Comment by pants97** [comment]
Thank you so much! =)
